keys:
  - &admin_chunix age1xjaws5828wj4qxmwzp0lt7azy4j9ftxjnv67wk644dvczknyu5xspmsuvl
  - &server_legion age13d9n4rmht23vsvpecjn2wzmzkzqmdqjz5je7gv4u5hsr3js6au5s92w7al
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_chunix
          - *server_legion
