keys:
  - &admin_chunix age1xjaws5828wj4qxmwzp0lt7azy4j9ftxjnv67wk644dvczknyu5xspmsuvl
  # - &admin_chunixy age172x77t8075uurrgf8f848khsn3q6s2xvefnmsanghayxqhwr83kqppkv3q
  - &admin_chunixy age155m4fu4umawdv5rmzhnqsdswu9fwaahh9zmx7rzwn202flfka5ms6f4t9x
  - &server_legion age13d9n4rmht23vsvpecjn2wzmzkzqmdqjz5je7gv4u5hsr3js6au5s92w7al
  - &server_yoga age1sz5ymsyjf8t2flqtqcqk0kd5ad2h9sjfgavvkpxuphzyhrygq5jqwgnnad
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_chunix
          - *admin_chunixy
          - *server_legion
          - *server_yoga
