{pkgs, lib, ...}: {
  environment.etc = {
    "pipewire.conf" = {
      enable = true;
      source = ./pipewire/pipewire.conf;
      mode = "0644";
      target = "pipewire.conf.d/pipewire.conf";
    };
    "pipewire-pulse.conf" = {
      enable = true;
      source = ./pipewire/pipewire-pulse.conf;
      mode = "0644";
      target = "pipewire.conf.d/pipewire-pulse.conf";
    };
  };
  services.pipewire = {
    enable = true;
    audio.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
		wireplumber. configPackages = let
          # generate "matches" section of the rules
          matches = lib.generators.toLua {
            multiline = false; # looks better while inline
            indent = false;
          } [[["node.name" "matches" "alsa_output.*"]]]; # nested lists are to produce `{{{ }}}` in the output

          # generate "apply_properties" section of the rules
          apply_properties = lib.generators.toLua {} {
            "audio.format" = "S32LE";
            "audio.rate" =  48000 * 2;
            "api.alsa.period-size" = 2;
          };
        in [
          (pkgs.writeTextDir "share/lowlatency.lua.d/99-alsa-lowlatency.lua" ''
            -- Generated by nix-gaming
            alsa_monitor.rules = {
              {
                matches = ${matches};
                apply_properties = ${apply_properties};
              }
            }
          '')
        ];
  };
}
