{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    thunderbird
    zotero
    logseq
    inkscape-with-extensions
    gimp
    bitwarden-cli
    libreoffice-fresh
    onedrive
    rnote
    pdfarranger
    yt-dlp
    wvkbd
    hyprpaper
    #obs-studio
    #davinci-resolve
    #discord-canary
    vesktop
    #skypeforlinux
    siyuan
    kdePackages.okular
    libsForQt5.xwaylandvideobridge
   	#ladybird
   	#ghostty
   	pfetch-rs
    #libsForQt5.kdenlive
    #inputs.nix-gaming.packages.${pkgs.system}.osu-lazer-bin
  ];
}
