{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    thunderbird
    zotero
    logseq
    inkscape-with-extensions
    gimp
    libreoffice-fresh
    onedrive
    rnote
    pdfarranger
    yt-dlp
    wvkbd
    wpaperd
    #obs-studio
    #davinci-resolve
    #discord-canary
    vesktop
    #skypeforlinux
    kdePackages.okular
    libsForQt5.xwaylandvideobridge
    #ladybird
    #ghostty
    pfetch-rs
    bitwarden-desktop
    syncthing
    #libsForQt5.kdenlive
    #inputs.nix-gaming.packages.${pkgs.system}.osu-lazer-bin
  ];
}
